### PR TITLE
Merges in latest from ros-planning navigation

### PR DESCRIPTION
**Pull request by KaijenHsiao**
The biggest change is removing the separate footprint_layer and rolling footprint clearing into the obstacle/voxel_layer.  But there are a lot of minor bugfixes and such in there also.

### CODE REVIEW

**Comment by haidai** [comment]
Eh... this seems really risky to do right before the demo. There are a lot of changes here.

**Comment by KaijenHsiao** [comment]
just try it.  We can always switch back.  Don't even have to merge until after.

**Comment by haidai** [comment]
Leaving this as separate branch for demo because of uncertainty about its stability after testing.
Needs:
https://github.com/mayfieldrobotics/gizmo_common/pull/61

**Comment by KaijenHsiao** [comment]
Even though we're not really using ROS nav anymore, I'd rather leave it up-to-date in case we ever want to try it again.  It was working just fine with the PR, we just didn't want to merge before the demo.  Should not affect anything we are currently using.

**Pull request merged**
